apiVersion: v1
kind: Service
metadata:
  labels:
    app: pages
    servicefor: pages
  name: pages
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pages
    servicefor: pages
  type: NodePort
status:
  loadBalancer: {}
